apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-lesson-ingress
spec:
  ingressClassName: test
  rules:
  - http:
      paths:
      - path: /users/*
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-users-svc
            port:
              number: 80
      - path: /products/*
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-products-svc
            port:
              number: 80