apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lesson-ingress
spec:
  ingressClassName: nginx # nginx ingress controller와 연결에 필요
  rules:
  - http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontweb-lesson-prod-svc
            port:
              number: 80
      - path: "/users/*"
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-users-svc
            port:
              number: 8080
      - path: "/products/*"
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-products-svc
            port:
              number: 8080

