apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path-basic
spec:
  ingressClassName: nginx # nginx ingress controller와 연결에 필요
  rules:
    - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontweb-lesson-prod-svc
            port: 80
    - http:
      paths:
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-users-svc
            port:
              number: 8080
    - http:
      paths:
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: backweb-lesson-products-svc
            port:
              number: 8080