apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules
  - http:
    paths:
    - path: /users/*
      backend:
        serviceName: backweb-lesson-users-svc
        servicePort: 80
    - path: /products/*
      backend:
        serviceName: backweb-lesson-products-svc
        servicePort: 80