apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontweb-lesson-prod
spec:
  selector:
    # Deployment 오브젝트가 파드를 관리할 때 사용하는 매핑 정보
    matchLabels:
      app: frontweb-lesson
      tier: frontend
      environment: production
  template:
    metadata:
      # 생설될 파드의 라벨 정보
      labels:
        app: frontweb-lesson
        tier: frontend
        environment: production
    spec:
      containers:
      - name: frontweb-lesson-prod-app
        image: gcr.io/crack-adapter-372504/gke-cicd-test-prod:test-1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontweb-lesson-prod-svc
spec:
  # 외부 트래픽을 전달할 파드의 라벨 정보
  selector:
    app: frontweb-lesson
    tier: frontend
    environment: production
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "35.243.125.162"