apiVersion: apps/v1
kind: Deployment
metadata:
  name: backweb-lesson-products
  # Deployment 오브젝트의 라벨 정보
  labels:
    app: backweb-lesson-products
spec:
  selector:
    # Deployment 오브젝트가 파드를 관리할 때 사용하는 매핑 정보
    matchLabels:
      app: backweb-lesson-products
  template:
    metadata:
      # 생설될 파드의 라벨 정보
      labels:
        app: backweb-lesson-products
    spec:
      containers:
      - name: fbackweb-lesson-products-app
        image: gcr.io/crack-adapter-372504/gke-cicd-test-prod:server-products
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backweb-lesson-products-svc
spec:
  selector:
    app: backweb-lesson-products
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
